[package]
name = "VHF"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "stream"

[[bin]]
name = "clear-fifo"
required-features = ["clear-fifo"]

[lib]
name = "vhf"

[features]
default = []
clear-fifo = ["nix/user", "prettytable-rs"]
o3 = ["VHF-parse/o3"]

[dependencies]
bytemuck = { version = "1.23.0" }
byteorder = "1.5.0"
clap = { version = "4.5.39", features = ["derive"] }
configparser = { version = "3.1.0", default-features = false }
evalexpr = { version = "12.0.2", features = ["regex"] }
heapless = { version = "0.8.0" }
itertools = { version = "0.14.0" }
jiff = { version = "0.2.13", features = ["alloc", "serde"] }
libc = { version = "0.2" }
log = { version = "0.4.22" }
log4rs = { version = "1.3.0", features = ["console_appender"] }
mmap-rs = { version = "0.6.1" }
nix = { version = "0.29.0", features = ["fs", "ioctl", "user"] }
num-traits = { version = "0.2.19" }
pariter = "0.5.1"
prettytable-rs = { version = "0.10.0", default-features = false, optional = true }
regex = { version = "1.11.1" }
serde = { version = "1.0.219" }
serde_json = { version = "1.0.140" }
VHF-common = { path = "common" }
VHF-parse = { path = "src/parser" }

[dev-dependencies]
approx = { version = "0.5.1" }
numpy = { version = "0.25.0" }
pyo3 = { version = "0.25.1", features = ["jiff-02"] }
tempfile = { version = "3.19.1", features = ["default"] }
test-log = { version = "0.2.17", features = ["trace", "color"] }
